name: $(Build.SourceBranch)$(Rev:.r)

trigger:
  - master

resources:
  containers:
  - container: linux
    image: ubuntu:16.04

jobs:
- job: Build
  displayName: Build Job
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: ShellScript@2
    displayName: Build
    inputs:
      scriptPath: 'tests/test_scripts/build.sh'

  - script: |
      echo "Sys.setenv(BATCH_ACCOUNT_NAME ='"$(BATCH_ACCOUNT_NAME)"');" >> /usr/lib/R/etc/Renviron
      echo "Sys.setenv(BATCH_ACCOUNT_KEY ='"$(BATCH_ACCOUNT_KEY)"');" >> /usr/lib/R/etc/Renviron
      echo "Sys.setenv(BATCH_ACCOUNT_URL ='"$(BATCH_ACCOUNT_URL)"');" >> /usr/lib/R/etc/Renviron
      echo "Sys.setenv(STORAGE_ACCOUNT_NAME ='"$(STORAGE_ACCOUNT_NAME)"');" >> /usr/lib/R/etc/Renviron
      echo "Sys.setenv(STORAGE_ACCOUNT_KEY ='"$(STORAGE_ACCOUNT_KEY)"');" >> /usr/lib/R/etc/Renviron
    condition: succeeded()
    displayName: Create R Profile Environment Setting

  - task: ShellScript@2
    displayName: Run Unit Tests
    inputs:
      scriptPath: 'tests/test_scripts/unit_tests.sh'
