name: $(Build.SourceBranch)$(Rev:.r)

trigger:
  - master

resources:
  containers:
  - container: linux
    image: ubuntu:16.04

jobs:
- job: Build
  displayName: Build Job
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: ShellScript@2
    displayName: Build
    inputs:
      scriptPath: 'tests/test_scripts/build.sh'

  - task: ShellScript@2
    displayName: 'Unit Tests'
    inputs:
      scriptPath: 'tests/test_scripts/unit_tests.sh'
